name: deploy_bot
env:
  SERVER: production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: $GITHUB_WORKSPACE

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        clean: false

    - name: Install npm packages
      run: npm install
    
    - name: Start/Reload PM2 service and run the app
      run: pm2 startOrReload $GITHUB_WORKSPACE/ecosystem.config.js --env $SERVER --cwd $GITHUB_WORKSPACE
